.\" Manpage for natstest.
.TH NATSTEST "1" "2016" "natstest" "User Commands"
.SH NAME
natstest \- NATS Test Component.
.SH DESCRIPTION
NATS Test Component.
.SS "Usage:"
.IP
natstest [flags]
natstest [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-c\fR, \fB\-\-configDir\fR=\fI10\fR: Configuration directory to be added on top of the search list
.HP
\fB\-l\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: panic, fatal, error, warning, info, debug
.HP
\fB\-s\fR, \fB\-\-serverAddress\fR=\fI10\fR: HTTP API URL (ip:port) or just (:port)
.HP
\fB\-n\fR, \fB\-\-natsAddress\fR=\fI10\fR: NATS bus Address (nats://ip:port)
.PP
Use "natstest [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
Nicola Asuni (nicola.asuni@miracl.com)
.SH COPYRIGHT
(c) 2016 MIRACL UK LTD
